### ISSUE TITLE
Crash after installing pod  for Vuukle 

### ISSUE THREAD

**Issue by SharonSelvasekar** [vuukle/ios_webview_sdk#1]
Hi,
I need to integrate Vuukle SDK in my project written in Objective C. The project has been developed from a lower version of Xcode . But now I have updated Xcode to Version 8.2.1 . I have installed the pod file as per the documentation.

platform :ios, '9.0'
target 'My_Project' do
   use_frameworks!
    pod 'Vuukle', :git => 'https://github.com/vuukle/vuukle_iOS_SDK.git', :branch => 'swift_3'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

After the pod installation, when I run the project, the app crashes.

This following is displayed:
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /var/containers/Bundle/Application/590FFFB5-2740-4948-AB8F-5AEEE6C402A1/MyProject.app/MyProject
  Reason: image not found

**Comment by lesukk** [comment]
We can't reproduce this issue and as crash reason you wrote is "Alamofire can't find image"
So please add more details when this crash happens (during command "pod install" or after running a project)
Also if you have a possibility, please record a broadcast of your screen.
Alamofire it's the other library which we use as dependency for you framework
Please make sure you placed the image in "Alamonfireimage" folder and not in "Alamonfire" folder.
![2017-02-03 20 41 22](https://cloud.githubusercontent.com/assets/19570032/22609670/c9f54fc2-ea6a-11e6-83ff-2a81fd555bbb.png)

**Comment by karthisiva** [comment]
@lesukk After successful pod installation when I run the project the following  crash" dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire" occurred. 
So I tried to solve  this crash by deintegrating and re-installing the pod file. But it was a temporary fix only.

 For the first time when I run the project, the project builds and runs successfully. Afterwards, after few successful times running the app , the application crashes randomly ("dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire"). 

To recover from this  I have to delete the app from the device/simulator and reinstall and it works fine. And this lasts for few times so I can run the app and again it crashes and I have to uninstall and reinstall the app.

**Comment by b13markus** [comment]
Did you add alomofire to your project podfile ?
If yes then you should remove it.

**Comment by karthisiva** [comment]
No, i am not using alomofire. we cant reprouduce it.
