### ISSUE TITLE
Post comment not working, i am not able to post comment???

### ISSUE THREAD

**Issue by karthisiva** [vuukle/ios_webview_sdk#2]
I have integrated vuukle Sdk through the pod file, Its version 2.0.26.Everthing okay, after entering user name and passowrd, i am clicking post button but that  does nothing just receving actions.
No loader showing, no output, nothing, comment not posting, replay comment also not posting. Like and Unlike also not working.
How to downgrade the vuukle version?
What should be the reason?

**Comment by lesukk** [comment]
Hello Karthisiva,
My skype id is lesukk2. I will be glad to help. Please add me on skype to help you resolve the issue.

**Comment by karthisiva** [comment]
I given request to your skype id. share some project in swif3, it would be much helpful
